name: Build and Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .editorconfig
      - .gitignore
      - .eslintrc.js

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BUILD_OUTPUT_PATH: dist
      PUBLISH_REPO_PATH: publish
      PUBLISH_REPO: ODonoghueLab/Cancer_XR
      PUBLISH_BRANCH: gh-pages
      VUE_APP_STATIC_SPA_MODE: true
      AQUARIA_CLIENT_EMIT_CNAME: cancer.aquaria.app

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2

    - name: Checkout publish repo
      uses: actions/checkout@v2
      with:
        repository: ${{ env.PUBLISH_REPO }}
        ref: ${{ env.PUBLISH_BRANCH }}
        path: '${{ env.PUBLISH_REPO_PATH }}'
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Clean publish repo
      working-directory: ${{ env.PUBLISH_REPO_PATH }}
      run: |
        git rm -rf .
        git clean -fxd
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: npm install

    - name: Build client
      run: npm run build

    - name: Copy build
      run: 'cp -r ${{ env.BUILD_OUTPUT_PATH }}/* ${{ env.PUBLISH_REPO_PATH }}'

    - name: Check for changes
      working-directory: ${{ env.PUBLISH_REPO_PATH }}
      run: |
        git add .
        git status
        [[ -z $(git status --porcelain) ]] || echo "::set-output name=changed::true"
      id: check_changes

    - name: Update publish repo
      if: steps.check_changes.outputs.changed
      working-directory: ${{ env.PUBLISH_REPO_PATH }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Deploy $GITHUB_SHA"
    - name: Deploy to Pages
      if: steps.check_changes.outputs.changed
      uses: ad-m/github-push-action@v0.6.0
      with:
        directory: ${{ env.PUBLISH_REPO_PATH }}
        repository: ${{ env.PUBLISH_REPO }}
        branch: ${{ env.PUBLISH_BRANCH }}
        github_token: ${{ secrets.PUBLISH_ACCESS_TOKEN }}
